In [1]:
print("welcome")

welcome


In [2]:
import numpy as np

In [3]:
list = [1,2,3]
list

[1, 2, 3]

In [5]:
np.array(list)

array([1, 2, 3])

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,4)

array([0, 4, 8])

In [11]:
np.arange(100,150,7)

array([100, 107, 114, 121, 128, 135, 142, 149])

In [12]:
np.arange(100,150,5)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [19]:
np.linspace(1000,2000,25)

array([1000.        , 1041.66666667, 1083.33333333, 1125.        ,
       1166.66666667, 1208.33333333, 1250.        , 1291.66666667,
       1333.33333333, 1375.        , 1416.66666667, 1458.33333333,
       1500.        , 1541.66666667, 1583.33333333, 1625.        ,
       1666.66666667, 1708.33333333, 1750.        , 1791.66666667,
       1833.33333333, 1875.        , 1916.66666667, 1958.33333333,
       2000.        ])

In [20]:
np.linspace(1,2,50)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.35214509, 0.75677278, 0.44569666, 0.28855123, 0.83681914])

In [24]:
np.random.rand(1,10,10)

array([[[0.75773796, 0.67472445, 0.2643653 , 0.95736351, 0.65651528,
         0.77814771, 0.39460923, 0.34964436, 0.89566422, 0.67122779],
        [0.89539568, 0.63330142, 0.50671391, 0.96822772, 0.79347123,
         0.87510792, 0.73068153, 0.47505364, 0.17654237, 0.1485157 ],
        [0.71652387, 0.50061764, 0.85776532, 0.24452402, 0.32850693,
         0.37124338, 0.15796059, 0.02227133, 0.88647539, 0.25596077],
        [0.49948698, 0.05904519, 0.68869997, 0.15296415, 0.51268574,
         0.89522587, 0.15439586, 0.88869008, 0.65325786, 0.20000379],
        [0.5359306 , 0.20345605, 0.50569964, 0.38168659, 0.40761156,
         0.61377597, 0.45723381, 0.74700451, 0.02922948, 0.52352793],
        [0.31929034, 0.35758369, 0.26860233, 0.74074239, 0.3332274 ,
         0.97998518, 0.45066375, 0.38940634, 0.16131425, 0.7795914 ],
        [0.55463722, 0.50969036, 0.6249577 , 0.61269867, 0.70329182,
         0.26687183, 0.52505564, 0.96899551, 0.46059912, 0.40254339],
        [0.9786277 , 0.4326

In [25]:
np.random.rand(5,5)

array([[0.18883658, 0.21391872, 0.20224966, 0.80536318, 0.1014906 ],
       [0.65544932, 0.30516404, 0.15325974, 0.52517754, 0.1714172 ],
       [0.94258881, 0.74385496, 0.81572366, 0.85855794, 0.80722333],
       [0.29900804, 0.2444122 , 0.33016137, 0.00232013, 0.35800548],
       [0.70932089, 0.84803109, 0.96059776, 0.96418697, 0.88434586]])

In [26]:
np.random.randn(5)

array([-0.79814971, -0.39074491, -0.03220776, -1.67690647, -0.00592398])

In [27]:
np.random.randint(3,6)

4

In [28]:
np.random.randint(1,10,5)

array([5, 2, 2, 2, 7])

In [29]:
np.random.randint(10,25)

21

In [31]:
arr = np.random.randint(0,50,15)
arr

array([49, 17, 34, 19, 41,  3, 39, 11, 15, 31, 18, 10, 41,  5,  4])

In [32]:
arr.shape

(15,)

In [35]:
arr.reshape(3,5)

array([[49, 17, 34, 19, 41],
       [ 3, 39, 11, 15, 31],
       [18, 10, 41,  5,  4]])

In [34]:
arr.reshape(5,3)

array([[49, 17, 34],
       [19, 41,  3],
       [39, 11, 15],
       [31, 18, 10],
       [41,  5,  4]])

20 Elements between 200 and 500. shape of the array. reshape the array.

In [38]:
arr1 = np.random.randint(200,500,20)
arr1

array([431, 269, 356, 489, 389, 302, 262, 239, 326, 452, 362, 343, 239,
       218, 232, 420, 340, 244, 364, 455])

In [39]:
arr1.shape

(20,)

In [40]:
arr1.reshape(2,10)

array([[431, 269, 356, 489, 389, 302, 262, 239, 326, 452],
       [362, 343, 239, 218, 232, 420, 340, 244, 364, 455]])

In [41]:
arr1.reshape(1,20)

array([[431, 269, 356, 489, 389, 302, 262, 239, 326, 452, 362, 343, 239,
        218, 232, 420, 340, 244, 364, 455]])

In [42]:
arr1.reshape(4,5)

array([[431, 269, 356, 489, 389],
       [302, 262, 239, 326, 452],
       [362, 343, 239, 218, 232],
       [420, 340, 244, 364, 455]])

In [43]:
arr1.reshape(5,4)

array([[431, 269, 356, 489],
       [389, 302, 262, 239],
       [326, 452, 362, 343],
       [239, 218, 232, 420],
       [340, 244, 364, 455]])

In [44]:
arr1.reshape(20,1)

array([[431],
       [269],
       [356],
       [489],
       [389],
       [302],
       [262],
       [239],
       [326],
       [452],
       [362],
       [343],
       [239],
       [218],
       [232],
       [420],
       [340],
       [244],
       [364],
       [455]])

In [45]:
arr1.reshape(10,2)

array([[431, 269],
       [356, 489],
       [389, 302],
       [262, 239],
       [326, 452],
       [362, 343],
       [239, 218],
       [232, 420],
       [340, 244],
       [364, 455]])

In [46]:
arr1.dtype

dtype('int32')

In [48]:
arr1[::-1]

array([455, 364, 244, 340, 420, 232, 218, 239, 343, 362, 452, 326, 239,
       262, 302, 389, 489, 356, 269, 431])